// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Optional in dev (Prisma manages an ad-hoc shadow DB locally during
    // `prisma migrate dev`). Required in CI for `prisma migrate diff
    // --from-migrations` — see docs/database.md → "CI Validation".
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
